name: jr cms 16 CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # mongodb-version: ['4','5']

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: install dependencies
        run: npm install

      - run: npm test
